---
- hosts: all
  gather_facts: True
  tasks:
    - name: Facts have been gathered
      debug:
        msg: "Facts are now gathered"

    - name: simple ping
      ping:
      register: results

    - name: debug
      debug:
        msg: results
