---
- name: Service Down - Restart Service
  hosts: "{{ _hosts }}"
  #hosts: ip-10-0-0-120
  #hosts: webservers
  become: true
  gather_facts: False

  tasks:
    - name: Show _hosts
      debug:
        var: _hosts

    - name: Start service, if not started
      ansible.builtin.service:
        name: firewalld
        state: started
      register: service_results
